### ISSUE TITLE
Cannot request a read scope with a client which was granted the write scope

### ISSUE THREAD

**Issue by ChristopherMann** [eryph-org/eryph#277] opened 2024-11-08 17:43 UTC
When an identity has been granted a write scope (e.g. `compute:write`), it cannot request the corresponding readonly scope (e.g. `compute.read`). The token endpoint returns the following error: This client application is not allowed to use the specified scope.

[AB#724](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/724)

**Comment by fw2568** [comment] 2024-11-11 10:12
In general, this is normal behavior for an identity service, since it cannot know the hierarchical relationship of the scopes. A Microsoft Identity Provider will behave the same way - if you want to allow a client to explicitly request reduced scopes, you have to add this to the scopes.

Where does this behavior actually cause a problem? For Powershell clients, we do not pass requested scopes at all, so automatically only available scopes are granted.

**Comment by ChristopherMann** [comment] 2024-11-11 10:32
The behavior does not cause any problems. I noticed it when using `Get-EryphAccessToken` with the system client and trying to request a read-only access token.

**Comment by fw2568** [comment] 2024-11-11 11:02
Ok, close this as it is expected behavior.

**Closed by fw2568** 2024-11-11 11:02 UTC
