### ISSUE TITLE
Install command renames OVS package in installation package

### ISSUE THREAD

**Issue by ChristopherMann** [eryph-org/eryph#127] opened 2024-02-06 13:43 UTC
The `eryph-zero.exe install` command renames the `ovspackage.zip` in the extracted installation package. This prevents reuse of the extracted installation package.

Replication procedure:
1. Download the eryph-zero installation package
2. Extract the eryph-zero installation package
3. Run `eryph-zero.exe install` in the extracted folder

Afterwards, `ovspackage.zip`  has been renamed to `ovspackage_backup.zip` in the extracted installation package.

[AB#582](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/582)

**Comment by fw2568** [comment] 2024-02-18 12:31
This is actually by design, as it prevents the package from being upgraded more than once.
Also, it is not the standard installation procedure to call install directly, as the installation should normally use the installer script. 
The script doesn't have a problem here, as it always extracts the files to a new folder.

I understand that this a problem for testing, but only for this special case. 

So I would say currently: wont fix

**Comment by fw2568** [comment] 2024-09-11 11:17
@ChristopherMann could you please recheck this issue if it is something we have actually to solve?

**Comment by fw2568** [comment] 2024-09-11 14:04
moving to beta.1 milestone - check if its quick to solve by keeping filename.

**Closed** 2024-09-18 13:02 UTC
